/**
 * Follow-up batch after Batch 11 — Priority 7 (comprehensive General Sales
 * CSV) and Priority 9 (PDF export). Tests buildSalesReportCsv and
 * buildSalesReportHtml directly — both are pure string-building functions
 * with no Electron/DOM dependency (same pattern as receiptBatch9.test.ts).
 * The PDF itself is generated by Electron's printToPDF from this HTML
 * (electron/services/pdfService.ts), so testing the HTML content is the
 * correct level — the rendering step is Electron's own, already-stable API.
 */
import { describe, it, expect } from 'vitest';
import { buildSalesReportCsv, buildSalesReportHtml, type SalesReportData } from '../src/utils/salesReport';
import type { Settings, ReportSummary, PartnerReport, ConsumptionReport, PaymentReport, ServiceChargeReport } from '../src/types';

function baseSettings(): Settings {
  return {
    id: 1,
    restaurantName: 'Test Restaurant',
    address: '',
    phone: '',
    taxPercentage: 0,
    currencySymbol: 'Rs',
    receiptFooter: '',
    darkMode: false,
    receiptPaperSize: '80mm',
    backupSchedule: 'daily',
    backupOnExit: true,
    cloudBackupEnabled: false,
    logoPath: null,
    currencyCode: 'PKR',
    receiptShowLogo: true,
    serviceChargePresets: null,
    googleReviewUrl: null,
    googleReviewOnReceipt: false,
    printerDeviceName: null,
  };
}

function baseSummary(overrides: Partial<ReportSummary> = {}): ReportSummary {
  return {
    revenue: 85000,
    orderCount: 45,
    averageOrderValue: 1888.89,
    totalDiscount: 2000,
    totalTax: 3000,
    totalSubtotal: 80000,
    totalServiceCharge: 1500,
    totalDue: 86500,
    daily: [],
    ...overrides,
  };
}

function baseData(overrides: Partial<SalesReportData> = {}): SalesReportData {
  const emptyPartner: PartnerReport = { partners: [], grandTotal: 0 };
  const emptyConsumption: ConsumptionReport = {
    orders: [],
    byPerson: [],
    totals: { ownerTotal: 0, employeeTotal: 0, combinedTotal: 0, orderCount: 0 },
  };
  const emptyPayments: PaymentReport = {
    payments: [],
    byMethod: [],
    totals: { totalCash: 0, totalOnline: 0, totalCollected: 0 },
  };
  const emptyServiceCharges: ServiceChargeReport = {
    orders: [],
    daily: [],
    periodTotal: 0,
    orderCount: 0,
    fixedCount: 0,
    fixedTotal: 0,
    percentageCount: 0,
    percentageTotal: 0,
  };
  return {
    from: '2026-08-20',
    to: '2026-08-30',
    settings: baseSettings(),
    summary: baseSummary(),
    partnerReport: emptyPartner,
    consumption: emptyConsumption,
    paymentReport: emptyPayments,
    serviceChargeReport: emptyServiceCharges,
    ...overrides,
  };
}

const samplePartnerReport: PartnerReport = {
  partners: [
    {
      partnerId: 1,
      partnerName: 'Partner A',
      items: [{ name: 'Burger', quantity: 20, sales: 20000, effectivePercentage: 50, partnerShare: 10000 }],
      totalShare: 10000,
    },
    {
      partnerId: 2,
      partnerName: 'Partner B',
      items: [{ name: 'Pizza', quantity: 10, sales: 10000, effectivePercentage: 30, partnerShare: 3000 }],
      totalShare: 3000,
    },
  ],
  grandTotal: 13000,
};

const samplePaymentReport: PaymentReport = {
  payments: [],
  byMethod: [
    { method: 'CASH', accountDisplayName: null, amount: 85000, count: 35 },
    { method: 'EASYPAISA', accountDisplayName: 'Restaurant Easypaisa', amount: 27000, count: 12 },
    { method: 'BANK', accountDisplayName: 'ABC Bank', amount: 18500, count: 8 },
  ],
  totals: { totalCash: 85000, totalOnline: 45500, totalCollected: 130500 },
};

const sampleConsumption: ConsumptionReport = {
  orders: [],
  byPerson: [
    {
      consumptionPersonId: 1,
      personName: 'John (Employee)',
      orderType: 'EMPLOYEE_CONSUMPTION',
      orderCount: 2,
      quantity: 3,
      value: 1500,
      items: [
        { name: 'Burger', quantity: 2, value: 1000 },
        { name: 'Fries', quantity: 1, value: 500 },
      ],
    },
  ],
  totals: { ownerTotal: 0, employeeTotal: 1500, combinedTotal: 1500, orderCount: 2 },
};

describe('buildSalesReportCsv', () => {
  it('includes the sales summary section with every required field', () => {
    const csv = buildSalesReportCsv(baseData());
    expect(csv).toContain('SALES SUMMARY');
    expect(csv).toContain('Total Orders');
    expect(csv).toContain('45');
    expect(csv).toContain('Total Revenue');
    expect(csv).toContain('85000.00');
    expect(csv).toContain('Subtotal');
    expect(csv).toContain('80000.00');
    expect(csv).toContain('Discounts');
    expect(csv).toContain('2000.00');
    expect(csv).toContain('Tax');
    expect(csv).toContain('3000.00');
    expect(csv).toContain('Service Charges');
    expect(csv).toContain('1500.00');
    expect(csv).toContain('Total Due');
    expect(csv).toContain('86500.00');
  });

  it('includes every partner without requiring a partner filter to be applied first', () => {
    const csv = buildSalesReportCsv(baseData({ partnerReport: samplePartnerReport }));
    expect(csv).toContain('PARTNER SHARES');
    expect(csv).toContain('Partner A');
    expect(csv).toContain('Partner B');
    expect(csv).toContain('10000.00');
    expect(csv).toContain('3000.00');
    expect(csv).toContain('13000.00'); // grand total
  });

  it('includes item-level consumption rows with person, type, item, quantity, value', () => {
    const csv = buildSalesReportCsv(baseData({ consumption: sampleConsumption }));
    expect(csv).toContain('OWNER / EMPLOYEE CONSUMPTION');
    expect(csv).toContain('John (Employee)');
    expect(csv).toContain('Employee');
    expect(csv).toContain('Burger');
    expect(csv).toContain('Fries');
    expect(csv).toContain('1000.00');
    expect(csv).toContain('500.00');
  });

  it('includes real payment methods with counts and totals — never invents a method', () => {
    const csv = buildSalesReportCsv(baseData({ paymentReport: samplePaymentReport }));
    expect(csv).toContain('PAYMENT BREAKDOWN');
    expect(csv).toContain('CASH');
    expect(csv).toContain('35');
    expect(csv).toContain('85000.00');
    expect(csv).toContain('EASYPAISA');
    expect(csv).toContain('12');
    expect(csv).toContain('BANK');
    expect(csv).toContain('8');
    expect(csv).not.toContain('CREDIT_CARD');
    expect(csv).not.toContain('PAYPAL');
  });

  it('includes service charge fixed/percentage breakdown', () => {
    const csv = buildSalesReportCsv(
      baseData({
        serviceChargeReport: {
          orders: [],
          daily: [],
          periodTotal: 1500,
          orderCount: 12,
          fixedCount: 5,
          fixedTotal: 500,
          percentageCount: 7,
          percentageTotal: 1000,
        },
      })
    );
    expect(csv).toContain('SERVICE CHARGE INFORMATION');
    expect(csv).toContain('Orders with Service Charge');
    expect(csv).toContain('12');
    expect(csv).toContain('Fixed Charges');
    expect(csv).toContain('Percentage Charges');
  });

  it('clearly states when a section has no data, rather than an empty/broken table', () => {
    const csv = buildSalesReportCsv(baseData());
    expect(csv).toContain('No partner-owned sales in this period.');
    expect(csv).toContain('No owner or employee consumption in this period.');
    expect(csv).toContain('No payments recorded in this period.');
  });

  it('shows the correct period label for a single date vs a date range', () => {
    const single = buildSalesReportCsv(baseData({ from: '2026-08-25', to: '2026-08-25' }));
    const range = buildSalesReportCsv(baseData({ from: '2026-08-20', to: '2026-08-30' }));
    expect(single).toContain('Aug 25, 2026');
    expect(single).not.toContain('–');
    expect(range).toContain('Aug 20, 2026 – Aug 30, 2026');
  });
});

describe('buildSalesReportHtml', () => {
  it('produces a formatted HTML document, not a raw CSV dump', () => {
    const html = buildSalesReportHtml(baseData({ partnerReport: samplePartnerReport, consumption: sampleConsumption, paymentReport: samplePaymentReport }));
    expect(html).toMatch(/^<!doctype html>/i);
    expect(html).toContain('<h1>General Sales Report</h1>');
    expect(html).toContain('<h2>Sales Summary</h2>');
    expect(html).toContain('<h2>Partner Shares</h2>');
    expect(html).toContain('<h2>Owner / Employee Consumption</h2>');
    expect(html).toContain('<h2>Payment Breakdown</h2>');
    expect(html).toContain('<h2>Service Charge Information</h2>');
    expect(html).toContain('<table');
    expect(html).not.toContain('Metric,Value'); // not just the CSV text embedded
  });

  it('includes every partner and every consumption person by name', () => {
    const html = buildSalesReportHtml(baseData({ partnerReport: samplePartnerReport, consumption: sampleConsumption }));
    expect(html).toContain('Partner A');
    expect(html).toContain('Partner B');
    expect(html).toContain('John (Employee)');
    expect(html).toContain('Fries');
  });

  it('escapes HTML-significant characters in names', () => {
    const html = buildSalesReportHtml(
      baseData({
        settings: { ...baseSettings(), restaurantName: 'Bob & Sons <Restaurant>' },
      })
    );
    expect(html).toContain('Bob &amp; Sons &lt;Restaurant&gt;');
    expect(html).not.toContain('<Restaurant>');
  });
});
